# Generated by Django 5.2.11 on 2026-03-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteImportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="imports/")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("completed_with_errors", "Con errores"),
                        ],
                        default="processing",
                        max_length=25,
                    ),
                ),
                ("log_errores", models.JSONField(blank=True, default=list)),
                ("total_registros", models.IntegerField(default=0)),
                ("creados", models.IntegerField(default=0)),
                ("actualizados", models.IntegerField(default=0)),
                ("con_error", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lotes",
                        to="institutions.institucion",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lotes_importacion",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="EstudianteImportado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="importaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudiantes",
                        to="imports.loteimportacion",
                    ),
                ),
            ],
            options={
                "db_table": "estudiantes_importados",
            },
        ),
    ]
