# Generated by Django 5.2.11 on 2026-03-03 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("url_externa", models.URLField(blank=True)),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "area_trabajo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.areatrabajo",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacantes",
                        to="companies.empresa",
                    ),
                ),
                (
                    "estado_vacante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.estadovacante",
                    ),
                ),
                (
                    "modalidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.modalidad",
                    ),
                ),
                (
                    "tipo_contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.tipocontrato",
                    ),
                ),
                (
                    "tipo_puesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.tipopuesto",
                    ),
                ),
                (
                    "tipo_vacante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.tipovacante",
                    ),
                ),
            ],
            options={
                "db_table": "vacantes",
                "ordering": ["-fecha_publicacion"],
                "indexes": [
                    models.Index(
                        fields=["estado_vacante"], name="vacantes_estado__19e014_idx"
                    ),
                    models.Index(
                        fields=["area_trabajo"], name="vacantes_area_tr_af0470_idx"
                    ),
                    models.Index(
                        fields=["-fecha_publicacion"],
                        name="vacantes_fecha_p_5c75c0_idx",
                    ),
                ],
            },
        ),
    ]
