# Generated by Django 5.2.11 on 2026-03-03 06:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Nombre del rol"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="UsuarioRol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de asignación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol de usuario",
                "verbose_name_plural": "Roles de usuario",
                "db_table": "usuario_roles",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Teléfono"),
                            ("google", "Google"),
                        ],
                        default="email",
                        max_length=10,
                        verbose_name="Método de autenticación",
                    ),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, verbose_name="Consentimiento otorgado"
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de consentimiento"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "soft_deleted",
                    models.BooleanField(default=False, verbose_name="Eliminado (soft)"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos extra"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PerfilAspirante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre completo"
                    ),
                ),
                (
                    "resumen_profesional",
                    models.TextField(blank=True, verbose_name="Resumen profesional"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ubicación"
                    ),
                ),
                (
                    "consentimiento_datos",
                    models.BooleanField(
                        default=False, verbose_name="Consentimiento de datos"
                    ),
                ),
                (
                    "fecha_consentimiento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de consentimiento"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos extra"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "estado_laboral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aspirantes",
                        to="catalogs.estadolaboral",
                        verbose_name="Estado laboral",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_aspirante",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de aspirante",
                "verbose_name_plural": "Perfiles de aspirantes",
                "db_table": "perfiles_aspirantes",
            },
        ),
        migrations.CreateModel(
            name="PerfilPracticante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Periodo inicio"
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(blank=True, null=True, verbose_name="Periodo fin"),
                ),
                (
                    "horas_requeridas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Horas requeridas"
                    ),
                ),
                (
                    "cargado_por_institucion",
                    models.BooleanField(
                        default=False, verbose_name="Cargado por institución"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos extra"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "estado_practica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="practicantes",
                        to="catalogs.estadopractica",
                        verbose_name="Estado de práctica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de practicante",
                "verbose_name_plural": "Perfiles de practicantes",
                "db_table": "perfiles_practicantes",
            },
        ),
    ]
