# Generated by Django 5.2.11 on 2026-03-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("catalogs", "0001_initial"),
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilpracticante",
            name="institucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="practicantes",
                to="institutions.institucion",
                verbose_name="Institución",
            ),
        ),
        migrations.AddField(
            model_name="perfilpracticante",
            name="nivel_academico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="practicantes",
                to="catalogs.nivelacademico",
                verbose_name="Nivel académico",
            ),
        ),
        migrations.AddField(
            model_name="perfilpracticante",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="practicantes",
                to="institutions.programaformacion",
                verbose_name="Programa de formación",
            ),
        ),
        migrations.AddField(
            model_name="perfilpracticante",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_practicante",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="usuariorol",
            name="rol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_roles",
                to="accounts.rol",
                verbose_name="Rol",
            ),
        ),
        migrations.AddField(
            model_name="usuariorol",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuario_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="usuariorol",
            constraint=models.UniqueConstraint(
                fields=("usuario", "rol"), name="unique_usuario_rol"
            ),
        ),
    ]
