# Generated by Django 5.2.11 on 2026-03-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
        ("cv", "0001_initial"),
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
            ],
            options={
                "db_table": "etiquetas",
            },
        ),
        migrations.CreateModel(
            name="Postulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visto", models.BooleanField(default=False)),
                ("fecha_postulacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cv_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cv.cvversion",
                    ),
                ),
                (
                    "estado_actual",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.estadopostulacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postulaciones",
                        to="jobs.vacante",
                    ),
                ),
            ],
            options={
                "db_table": "postulaciones",
            },
        ),
        migrations.CreateModel(
            name="HistorialPostulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.estadopostulacion",
                    ),
                ),
                (
                    "postulacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="applications.postulacion",
                    ),
                ),
            ],
            options={
                "db_table": "historial_postulaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PostulacionEtiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etiqueta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.etiqueta",
                    ),
                ),
                (
                    "postulacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.postulacion",
                    ),
                ),
            ],
            options={
                "db_table": "postulacion_etiquetas",
            },
        ),
        migrations.AddField(
            model_name="postulacion",
            name="etiquetas",
            field=models.ManyToManyField(
                blank=True,
                through="applications.PostulacionEtiqueta",
                to="applications.etiqueta",
            ),
        ),
        migrations.AddConstraint(
            model_name="postulacionetiqueta",
            constraint=models.UniqueConstraint(
                fields=("postulacion", "etiqueta"), name="unique_postulacion_etiqueta"
            ),
        ),
        migrations.AddConstraint(
            model_name="postulacion",
            constraint=models.UniqueConstraint(
                fields=("vacante", "usuario"), name="unique_postulacion"
            ),
        ),
    ]
