# Generated by Django 5.2.11 on 2026-03-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        help_text="aspirante | practicante | empresa | institucion",
                        max_length=20,
                    ),
                ),
                ("field_name", models.SlugField(max_length=100)),
                ("field_label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("select", "Selección"),
                            ("checkbox", "Checkbox"),
                            ("date", "Fecha"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Opciones para tipo 'select'",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "dynamic_fields",
                "ordering": ["profile_type", "order"],
                "unique_together": {("profile_type", "field_name")},
            },
        ),
    ]
