// ─────────────────────────────────────────────
//  MOCK CONSTANTS – Dashboard + Vacancies
// ─────────────────────────────────────────────

export const MOCK_COMPANIES = [
  {
    id: 1,
    name: 'Tech Solutions CR S.A.',
    legalId: '3-101-789456',
    email: 'info@techsolutionscr.com',
    phone: '2256-7800',
    location: 'San José',
    contactName: 'Roberto Alvarado',
    registrationDate: '2023-03-10',
    status: 'aprobada',
  },
  {
    id: 2,
    name: 'Agro Tico Exportaciones Ltda.',
    legalId: '3-102-456123',
    email: 'ventas@agrotico.cr',
    phone: '2440-1155',
    location: 'Alajuela',
    contactName: 'Patricia Ugalde',
    registrationDate: '2023-07-22',
    status: 'aprobada',
  },
  {
    id: 3,
    name: 'Constructora Heredia S.A.',
    legalId: '3-101-321654',
    email: 'proyectos@constructoraheredia.com',
    phone: '2261-9900',
    location: 'Heredia',
    contactName: 'Mauricio Sancho',
    registrationDate: '2024-01-08',
    status: 'pendiente',
  },
  {
    id: 4,
    name: 'Logística Sur S.R.L.',
    legalId: '3-102-654987',
    email: 'operaciones@logisticasur.cr',
    phone: '2771-3344',
    location: 'Pérez Zeledón',
    contactName: 'Ana Ulate',
    registrationDate: '2024-04-19',
    status: 'pendiente',
  },
  {
    id: 5,
    name: 'Diseño Digital PYME S.A.',
    legalId: '3-101-112233',
    email: 'hola@diseniodigital.cr',
    phone: null,
    location: 'Curridabat',
    contactName: 'Natalia Esquivel',
    registrationDate: '2023-11-30',
    status: 'aprobada',
  },
  {
    id: 6,
    name: 'Turismo Guanacaste S.A.',
    legalId: '3-101-998877',
    email: 'reservas@turismoguanacaste.com',
    phone: '2668-5500',
    location: 'Liberia',
    contactName: 'Jorge Porras',
    registrationDate: '2023-05-14',
    status: 'desactivada',
  },
  {
    id: 7,
    name: 'Industrias Cartago S.A.',
    legalId: '3-101-776655',
    email: 'contacto@industriascartago.cr',
    phone: '2551-0022',
    location: 'Cartago',
    contactName: 'Silvia Montoya',
    registrationDate: '2024-08-01',
    status: 'aprobada',
  },
  {
    id: 8,
    name: 'Biofarma Limón S.R.L.',
    legalId: '3-102-334455',
    email: 'admin@biofarma.cr',
    phone: '2798-6611',
    location: 'Limón',
    contactName: 'Esteban Calvo',
    registrationDate: '2024-02-17',
    status: 'desactivada',
  },
];

export const MOCK_INSTITUTIONS = [
  {
    id: 1,
    name: 'Universidad de Costa Rica',
    type: 'universidad',
    email: 'admision@ucr.ac.cr',
    phone: '2511-4000',
    location: 'San José',
    contactName: 'Lic. Carmen Ruiz',
    registrationDate: '2022-01-10',
    status: 'aprobada',
  },
  {
    id: 2,
    name: 'Instituto Tecnológico de Costa Rica',
    type: 'universidad',
    email: 'info@itcr.ac.cr',
    phone: '2550-2000',
    location: 'Cartago',
    contactName: 'Dr. Álvaro Monge',
    registrationDate: '2022-03-05',
    status: 'aprobada',
  },
  {
    id: 3,
    name: 'Colegio Técnico Profesional de Limón',
    type: 'centro_tecnico',
    email: 'ctplimon@mep.go.cr',
    phone: '2758-3344',
    location: 'Limón',
    contactName: 'Prof. Sandra Acuña',
    registrationDate: '2023-02-20',
    status: 'aprobada',
  },
  {
    id: 4,
    name: 'Colegio Humanístico de Heredia',
    type: 'colegio',
    email: 'colegio.humanistico@mep.go.cr',
    phone: '2237-8800',
    location: 'Heredia',
    contactName: 'Prof. Marco Solís',
    registrationDate: '2023-06-15',
    status: 'pendiente',
  },
  {
    id: 5,
    name: 'Instituto Nacional de Aprendizaje – Alajuela',
    type: 'instituto',
    email: 'ina.alajuela@ina.ac.cr',
    phone: '2443-7700',
    location: 'Alajuela',
    contactName: 'Ing. Rosa Madriz',
    registrationDate: '2022-09-01',
    status: 'aprobada',
  },
  {
    id: 6,
    name: 'Universidad Técnica Nacional',
    type: 'universidad',
    email: 'info@utn.ac.cr',
    phone: '2211-0000',
    location: 'Atenas',
    contactName: 'Dra. Laura Varela',
    registrationDate: '2023-04-12',
    status: 'desactivada',
  },
  {
    id: 7,
    name: 'Centro de Formación Agrícola de Guanacaste',
    type: 'centro_tecnico',
    email: 'cfa.guanacaste@mep.go.cr',
    phone: '2665-1234',
    location: 'Liberia',
    contactName: 'Téc. Luis Fonseca',
    registrationDate: '2024-01-25',
    status: 'pendiente',
  },
  {
    id: 8,
    name: 'Colegio San Luis Gonzaga',
    type: 'colegio',
    email: 'sanluis@mep.go.cr',
    phone: '2551-0066',
    location: 'Cartago',
    contactName: 'Prof. Ivannia Torres',
    registrationDate: '2022-07-30',
    status: 'aprobada',
  },
];

export const MOCK_ASPIRANTS = [
  { id: 1, name: 'Andrea Solano Vargas',   email: 'andrea.solano@gmail.com',   phone: '8812-3456', location: 'San José',   registrationDate: '2024-08-15', status: 'activo'   },
  { id: 2, name: 'Carlos Méndez Jiménez',  email: 'carlos.mendez@hotmail.com', phone: '7734-9021', location: 'Cartago',    registrationDate: '2024-09-03', status: 'activo'   },
  { id: 3, name: 'Lucía Fernández Rojas',  email: 'lucia.fernandez@yahoo.com', phone: '6645-1122', location: 'Heredia',    registrationDate: '2024-07-20', status: 'inactivo' },
  { id: 4, name: 'Diego Mora Quesada',     email: 'diego.mora@gmail.com',      phone: '8890-4433', location: 'Alajuela',   registrationDate: '2024-10-11', status: 'activo'   },
  { id: 5, name: 'Valentina Castro Arias', email: 'vale.castro@outlook.com',   phone: null,        location: 'Liberia',    registrationDate: '2024-11-02', status: 'inactivo' },
  { id: 6, name: 'Sebastián Núñez Blanco', email: 'sebas.nunez@gmail.com',     phone: '7701-8877', location: 'Puntarenas', registrationDate: '2025-01-14', status: 'activo'   },
  { id: 7, name: 'María José Araya Pérez', email: 'mj.araya@gmail.com',        phone: '8823-5566', location: 'Curridabat', registrationDate: '2025-02-28', status: 'activo'   },
  { id: 8, name: 'Felipe Brenes Salas',    email: 'felipe.brenes@hotmail.com', phone: '6611-2200', location: 'Limón',      registrationDate: '2024-06-05', status: 'inactivo' },
];

export const MOCK_VACANCIES = [
  // ── Pendientes (aparecen en Vacancies.jsx) ──────────────────────────
  {
    id: 1,
    type: 'empleo',
    title: 'Desarrollador Frontend',
    companyName: 'Tech Solutions CR S.A.',
    requestedBy: 'Roberto Alvarado',
    description:
      'Buscamos un desarrollador Frontend con experiencia en React para unirse a nuestro equipo de producto. Trabajarás en el diseño e implementación de interfaces de usuario modernas, colaborando directamente con el equipo de diseño y backend.',
    requirements: [
      'Experiencia mínima de 2 años con React',
      'Conocimientos de HTML5, CSS3 y JavaScript ES6+',
      'Manejo de control de versiones con Git',
      'Capacidad de trabajo en equipo y metodologías ágiles',
    ],
    schedule: 'Lunes a Viernes',
    time: '8:00 am – 5:00 pm',
    isFullTime: true,
    location: 'San José',
    applicantsCount: 14,
    positionInfo: 'Posición permanente con posibilidad de trabajo remoto parcial. Salario competitivo y beneficios adicionales.',
    status: 'pendiente',
  },
  {
    id: 2,
    type: 'pasantia',
    title: 'Pasante de Análisis de Datos',
    companyName: 'Diseño Digital PYME S.A.',
    requestedBy: 'Natalia Esquivel',
    description:
      'Ofrecemos una pasantía de 6 meses orientada a estudiantes de Estadística, Ingeniería en Sistemas o carreras afines. El pasante apoyará el área de inteligencia de negocios y análisis de métricas de marketing digital.',
    requirements: [
      'Estudiante activo de últimos años de carrera',
      'Conocimientos básicos de SQL y Excel avanzado',
      'Deseable experiencia con Python o R',
      'Disponibilidad de al menos 20 horas semanales',
    ],
    schedule: 'Lunes a Viernes',
    time: '9:00 am – 1:00 pm',
    isFullTime: false,
    location: 'Curridabat',
    applicantsCount: 7,
    positionInfo: 'Pasantía remunerada con posibilidad de contratación al finalizar. Se entrega carta de recomendación.',
    status: 'pendiente',
  },
  {
    id: 3,
    type: 'empleo',
    title: 'Técnico Agrícola de Campo',
    companyName: 'Agro Tico Exportaciones Ltda.',
    requestedBy: 'Patricia Ugalde',
    description:
      'Requerimos un técnico agrícola para supervisar cultivos de exportación en la zona de Alajuela. El puesto implica visitas diarias a parcelas, monitoreo de plagas y coordinación con el equipo de empaque.',
    requirements: [
      'Título de Técnico en Agricultura o carrera afín',
      'Licencia de conducir B1 vigente',
      'Disponibilidad para trabajo en campo',
      'Conocimiento en manejo integrado de plagas',
    ],
    schedule: 'Lunes a Sábado',
    time: '6:00 am – 2:00 pm',
    isFullTime: true,
    location: 'Alajuela',
    applicantsCount: 5,
    positionInfo: 'Se provee transporte al lugar de trabajo. Uniforme y equipo de protección incluidos.',
    status: 'pendiente',
  },
  {
    id: 4,
    type: 'pasantia',
    title: 'Pasante de Recursos Humanos',
    companyName: 'Industrias Cartago S.A.',
    requestedBy: 'Silvia Montoya',
    description:
      'Pasantía orientada a estudiantes de Administración de Empresas o Psicología. Apoyará procesos de reclutamiento, inducción y bienestar laboral dentro del área de Recursos Humanos.',
    requirements: [
      'Estudiante universitario de 3er año en adelante',
      'Habilidades de comunicación y trabajo en equipo',
      'Manejo de Microsoft Office',
      'Actitud proactiva y discreción',
    ],
    schedule: 'Lunes a Viernes',
    time: '8:00 am – 12:00 md',
    isFullTime: false,
    location: 'Cartago',
    applicantsCount: 3,
    positionInfo: 'Pasantía de 4 meses con beca de transporte. Posibilidad de extensión según desempeño.',
    status: 'pendiente',
  },

  // ── Activas (para conteo en Dashboard) ──────────────────────────────
  {
    id: 5,
    type: 'empleo',
    title: 'Coordinador de Proyectos',
    companyName: 'Tech Solutions CR S.A.',
    requestedBy: 'Roberto Alvarado',
    description: 'Coordinación de proyectos tecnológicos con clientes nacionales e internacionales.',
    requirements: ['PMP o equivalente deseable', 'Experiencia en metodologías ágiles'],
    schedule: 'Lunes a Viernes',
    time: '8:00 am – 5:00 pm',
    isFullTime: true,
    location: 'San José',
    applicantsCount: 9,
    positionInfo: 'Posición de alta responsabilidad con beneficios de salud.',
    status: 'activa',
  },
  {
    id: 6,
    type: 'empleo',
    title: 'Operario de Logística',
    companyName: 'Logística Sur S.R.L.',
    requestedBy: 'Ana Ulate',
    description: 'Manejo de inventario y despacho de mercancía en bodega.',
    requirements: ['Bachillerato completo', 'Experiencia en bodega o logística'],
    schedule: 'Lunes a Sábado',
    time: '7:00 am – 4:00 pm',
    isFullTime: true,
    location: 'Pérez Zeledón',
    applicantsCount: 11,
    positionInfo: 'Incluye seguro médico y bono de productividad.',
    status: 'activa',
  },
  {
    id: 7,
    type: 'empleo',
    title: 'Diseñador UX/UI',
    companyName: 'Diseño Digital PYME S.A.',
    requestedBy: 'Natalia Esquivel',
    description: 'Diseño de experiencias digitales para clientes del sector comercial y educativo.',
    requirements: ['Portfolio requerido', 'Dominio de Figma o Adobe XD'],
    schedule: 'Lunes a Viernes',
    time: '9:00 am – 6:00 pm',
    isFullTime: true,
    location: 'Curridabat',
    applicantsCount: 6,
    positionInfo: 'Trabajo híbrido. Equipo de trabajo propio.',
    status: 'activa',
  },

  // ── Cerradas ─────────────────────────────────────────────────────────
  {
    id: 8,
    type: 'empleo',
    title: 'Guía Turístico',
    companyName: 'Turismo Guanacaste S.A.',
    requestedBy: 'Jorge Porras',
    description: 'Atención y guía de turistas en tours nacionales.',
    requirements: ['Inglés avanzado', 'Experiencia en turismo'],
    schedule: 'Variable',
    time: 'Según itinerario',
    isFullTime: false,
    location: 'Liberia',
    applicantsCount: 18,
    positionInfo: 'Posición estacional, alta temporada.',
    status: 'cerrada',
  },
  {
    id: 9,
    type: 'empleo',
    title: 'Regente Farmacéutico',
    companyName: 'Biofarma Limón S.R.L.',
    requestedBy: 'Esteban Calvo',
    description: 'Supervisión y control de procesos farmacéuticos.',
    requirements: ['Licenciatura en Farmacia', 'Incorporado al Colegio de Farmacéuticos'],
    schedule: 'Lunes a Viernes',
    time: '8:00 am – 5:00 pm',
    isFullTime: true,
    location: 'Limón',
    applicantsCount: 2,
    positionInfo: 'Plaza cubierta.',
    status: 'cerrada',
  },
];

export const MOCK_ADMINS = [
  {
    id: 1,
    name: 'Carlos Ramírez Solano',
    email: 'carlos.ramirez@admin.cr',
    role: 'superadmin',
    lastLogin: '2025-03-04 10:12',
  },
  {
    id: 2,
    name: 'Andrea Mora Jiménez',
    email: 'andrea.mora@admin.cr',
    role: 'admin',
    lastLogin: '2025-03-04 09:45',
  },
  {
    id: 3,
    name: 'Luis Arias Vega',
    email: 'luis.arias@admin.cr',
    role: 'admin',
    lastLogin: '2025-03-03 17:30',
  },
  {
    id: 4,
    name: 'Patricia Ugalde Campos',
    email: 'patricia.ugalde@admin.cr',
    role: 'admin',
    lastLogin: '2025-03-02 14:20',
  },
];

export const MOCK_AUDIT = [
  {
    id: 1,
    action: 'Vacante "Desarrollador Frontend" aprobada',
    type: 'cambio',
    userName: 'Admin Principal',
    userRole: 'Administrador',
    timestamp: '2025-03-04 10:35',
  },
  {
    id: 2,
    action: 'Nueva vacante pendiente: "Pasante de Análisis de Datos"',
    type: 'registro',
    userName: 'Sistema',
    userRole: 'Automático',
    timestamp: '2025-03-04 09:58',
  },
  {
    id: 3,
    action: 'Empresa "Tech Solutions CR S.A." aprobada',
    type: 'cambio',
    userName: 'Admin Principal',
    userRole: 'Administrador',
    timestamp: '2025-03-04 09:12',
  },
  {
    id: 4,
    action: 'Nueva institución pendiente: "Colegio Humanístico de Heredia"',
    type: 'registro',
    userName: 'Sistema',
    userRole: 'Automático',
    timestamp: '2025-03-04 08:47',
  },
  {
    id: 5,
    action: 'Vacante "Técnico Agrícola de Campo" rechazada',
    type: 'cambio',
    userName: 'Admin Principal',
    userRole: 'Administrador',
    timestamp: '2025-03-03 17:14',
  },
  {
    id: 6,
    action: 'Aspirante "Valentina Castro Arias" desactivada',
    type: 'cambio',
    userName: 'Admin Principal',
    userRole: 'Administrador',
    timestamp: '2025-03-03 16:30',
  },
  {
    id: 7,
    action: 'Nueva vacante pendiente: "Pasante de Recursos Humanos"',
    type: 'registro',
    userName: 'Sistema',
    userRole: 'Automático',
    timestamp: '2025-03-03 15:22',
  },
  {
    id: 8,
    action: 'Nueva empresa pendiente: "Logística Sur S.R.L."',
    type: 'registro',
    userName: 'Sistema',
    userRole: 'Automático',
    timestamp: '2025-03-03 14:05',
  },
  {
    id: 9,
    action: 'Vacante "Coordinador de Proyectos" aprobada',
    type: 'cambio',
    userName: 'Admin Principal',
    userRole: 'Administrador',
    timestamp: '2025-03-03 11:22',
  },
  {
    id: 10,
    action: 'Institución "Universidad Técnica Nacional" desactivada',
    type: 'cambio',
    userName: 'Admin Principal',
    userRole: 'Administrador',
    timestamp: '2025-03-02 17:00',
  },
];
