# Generated by Django 4.2.28 on 2026-03-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPasantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla Institución')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de pasantes')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('encargado', models.CharField(max_length=255, verbose_name='Encargado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_pasantia_recibidas', to='companies.empresa')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_pasantia_enviadas', to='institutions.institucion')),
            ],
            options={
                'verbose_name': 'Solicitud de Pasantía',
                'verbose_name_plural': 'Solicitudes de Pasantía',
                'db_table': 'solicitudes_pasantia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
