# Generated by Django 4.2.28 on 2026-03-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='enviado',
            field=models.BooleanField(default=False, verbose_name='Enviado (email/SMS)'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='', max_length=255, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url_accion',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='URL de acción'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.medionotificacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogs.tipoevento'),
        ),
    ]
