# Generated by Django 5.2.11 on 2026-03-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditoriaAccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acción de auditoría",
                "verbose_name_plural": "Acciones de auditoría",
                "db_table": "auditoria_acciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entidad auditable",
                "verbose_name_plural": "Entidades auditables",
                "db_table": "auditoria_entidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidad_id",
                    models.PositiveIntegerField(verbose_name="ID de la entidad"),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "accion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="audit.auditoriaaccion",
                        verbose_name="Acción",
                    ),
                ),
                (
                    "entidad_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="audit.auditoriaentidad",
                        verbose_name="Tipo de entidad",
                    ),
                ),
                (
                    "realizado_por_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auditoria_eventos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de auditoría",
                "verbose_name_plural": "Eventos de auditoría",
                "db_table": "auditoria_eventos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="AuditoriaEventoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=255, verbose_name="Campo")),
                (
                    "valor_anterior",
                    models.TextField(
                        blank=True, null=True, verbose_name="Valor anterior"
                    ),
                ),
                (
                    "valor_nuevo",
                    models.TextField(blank=True, null=True, verbose_name="Valor nuevo"),
                ),
                (
                    "auditoria_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="audit.auditoriaevento",
                        verbose_name="Evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de evento",
                "verbose_name_plural": "Detalles de evento",
                "db_table": "auditoria_evento_detalles",
            },
        ),
    ]
