// ─────────────────────────────────────────────
//  MOCK DATA – SearchAspirants / SearchCompanies / SearchInstitutions
// ─────────────────────────────────────────────

// ── Aspirantes ──────────────────────────────
export const mockAspirants = [
  {
    id: 1,
    name: 'Andrea Solano Vargas',
    email: 'andrea.solano@gmail.com',
    phone: '8812-3456',
    location: 'San José',
    registrationDate: '2024-08-15',
    status: 'activo',
  },
  {
    id: 2,
    name: 'Carlos Méndez Jiménez',
    email: 'carlos.mendez@hotmail.com',
    phone: '7734-9021',
    location: 'Cartago',
    registrationDate: '2024-09-03',
    status: 'activo',
  },
  {
    id: 3,
    name: 'Lucía Fernández Rojas',
    email: 'lucia.fernandez@yahoo.com',
    phone: '6645-1122',
    location: 'Heredia',
    registrationDate: '2024-07-20',
    status: 'inactivo',
  },
  {
    id: 4,
    name: 'Diego Mora Quesada',
    email: 'diego.mora@gmail.com',
    phone: '8890-4433',
    location: 'Alajuela',
    registrationDate: '2024-10-11',
    status: 'activo',
  },
  {
    id: 5,
    name: 'Valentina Castro Arias',
    email: 'vale.castro@outlook.com',
    phone: null,
    location: 'Liberia',
    registrationDate: '2024-11-02',
    status: 'inactivo',
  },
  {
    id: 6,
    name: 'Sebastián Núñez Blanco',
    email: 'sebas.nunez@gmail.com',
    phone: '7701-8877',
    location: 'Puntarenas',
    registrationDate: '2025-01-14',
    status: 'activo',
  },
  {
    id: 7,
    name: 'María José Araya Pérez',
    email: 'mj.araya@gmail.com',
    phone: '8823-5566',
    location: 'Curridabat',
    registrationDate: '2025-02-28',
    status: 'activo',
  },
  {
    id: 8,
    name: 'Felipe Brenes Salas',
    email: 'felipe.brenes@hotmail.com',
    phone: '6611-2200',
    location: 'Limón',
    registrationDate: '2024-06-05',
    status: 'inactivo',
  },
];

// ── Empresas ─────────────────────────────────
export const mockCompanies = [
  {
    id: 1,
    name: 'Tech Solutions CR S.A.',
    legalId: '3-101-789456',
    email: 'info@techsolutionscr.com',
    phone: '2256-7800',
    location: 'San José',
    contactName: 'Roberto Alvarado',
    registrationDate: '2023-03-10',
    status: 'aprobada',
  },
  {
    id: 2,
    name: 'Agro Tico Exportaciones Ltda.',
    legalId: '3-102-456123',
    email: 'ventas@agrotico.cr',
    phone: '2440-1155',
    location: 'Alajuela',
    contactName: 'Patricia Ugalde',
    registrationDate: '2023-07-22',
    status: 'aprobada',
  },
  {
    id: 3,
    name: 'Constructora Heredia S.A.',
    legalId: '3-101-321654',
    email: 'proyectos@constructoraheredia.com',
    phone: '2261-9900',
    location: 'Heredia',
    contactName: 'Mauricio Sancho',
    registrationDate: '2024-01-08',
    status: 'pendiente',
  },
  {
    id: 4,
    name: 'Logística Sur S.R.L.',
    legalId: '3-102-654987',
    email: 'operaciones@logisticasur.cr',
    phone: '2771-3344',
    location: 'Pérez Zeledón',
    contactName: 'Ana Ulate',
    registrationDate: '2024-04-19',
    status: 'pendiente',
  },
  {
    id: 5,
    name: 'Diseño Digital PYME S.A.',
    legalId: '3-101-112233',
    email: 'hola@diseniodigital.cr',
    phone: null,
    location: 'Curridabat',
    contactName: 'Natalia Esquivel',
    registrationDate: '2023-11-30',
    status: 'aprobada',
  },
  {
    id: 6,
    name: 'Turismo Guanacaste S.A.',
    legalId: '3-101-998877',
    email: 'reservas@turismoguanacaste.com',
    phone: '2668-5500',
    location: 'Liberia',
    contactName: 'Jorge Porras',
    registrationDate: '2023-05-14',
    status: 'desactivada',
  },
  {
    id: 7,
    name: 'Industrias Cartago S.A.',
    legalId: '3-101-776655',
    email: 'contacto@industriascartago.cr',
    phone: '2551-0022',
    location: 'Cartago',
    contactName: 'Silvia Montoya',
    registrationDate: '2024-08-01',
    status: 'aprobada',
  },
  {
    id: 8,
    name: 'Biofarma Limón S.R.L.',
    legalId: '3-102-334455',
    email: 'admin@biofarma.cr',
    phone: '2798-6611',
    location: 'Limón',
    contactName: 'Esteban Calvo',
    registrationDate: '2024-02-17',
    status: 'desactivada',
  },
];

// ── Instituciones ────────────────────────────
export const mockInstitutions = [
  {
    id: 1,
    name: 'Universidad de Costa Rica',
    type: 'universidad',
    email: 'admision@ucr.ac.cr',
    phone: '2511-4000',
    location: 'San José',
    contactName: 'Lic. Carmen Ruiz',
    registrationDate: '2022-01-10',
    status: 'aprobada',
  },
  {
    id: 2,
    name: 'Instituto Tecnológico de Costa Rica',
    type: 'universidad',
    email: 'info@itcr.ac.cr',
    phone: '2550-2000',
    location: 'Cartago',
    contactName: 'Dr. Álvaro Monge',
    registrationDate: '2022-03-05',
    status: 'aprobada',
  },
  {
    id: 3,
    name: 'Colegio Técnico Profesional de Limón',
    type: 'centro_tecnico',
    email: 'ctplimon@mep.go.cr',
    phone: '2758-3344',
    location: 'Limón',
    contactName: 'Prof. Sandra Acuña',
    registrationDate: '2023-02-20',
    status: 'aprobada',
  },
  {
    id: 4,
    name: 'Colegio Humanístico de Heredia',
    type: 'colegio',
    email: 'colegio.humanistico@mep.go.cr',
    phone: '2237-8800',
    location: 'Heredia',
    contactName: 'Prof. Marco Solís',
    registrationDate: '2023-06-15',
    status: 'pendiente',
  },
  {
    id: 5,
    name: 'Instituto Nacional de Aprendizaje – Alajuela',
    type: 'instituto',
    email: 'ina.alajuela@ina.ac.cr',
    phone: '2443-7700',
    location: 'Alajuela',
    contactName: 'Ing. Rosa Madriz',
    registrationDate: '2022-09-01',
    status: 'aprobada',
  },
  {
    id: 6,
    name: 'Universidad Técnica Nacional',
    type: 'universidad',
    email: 'info@utn.ac.cr',
    phone: '2211-0000',
    location: 'Atenas',
    contactName: 'Dra. Laura Varela',
    registrationDate: '2023-04-12',
    status: 'desactivada',
  },
  {
    id: 7,
    name: 'Centro de Formación Agrícola de Guanacaste',
    type: 'centro_tecnico',
    email: 'cfa.guanacaste@mep.go.cr',
    phone: '2665-1234',
    location: 'Liberia',
    contactName: 'Téc. Luis Fonseca',
    registrationDate: '2024-01-25',
    status: 'pendiente',
  },
  {
    id: 8,
    name: 'Colegio San Luis Gonzaga',
    type: 'colegio',
    email: 'sanluis@mep.go.cr',
    phone: '2551-0066',
    location: 'Cartago',
    contactName: 'Prof. Ivannia Torres',
    registrationDate: '2022-07-30',
    status: 'aprobada',
  },
];
