# Generated by Django 5.2.11 on 2026-03-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Área de trabajo",
                "verbose_name_plural": "Áreas de trabajo",
                "db_table": "areas_trabajo",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estado laboral",
                "verbose_name_plural": "Estados laborales",
                "db_table": "estados_laborales",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoPostulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estado de postulación",
                "verbose_name_plural": "Estados de postulación",
                "db_table": "estados_postulacion",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoPractica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estado de práctica",
                "verbose_name_plural": "Estados de práctica",
                "db_table": "estados_practica",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstadoVacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estado de vacante",
                "verbose_name_plural": "Estados de vacante",
                "db_table": "estados_vacante",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedioNotificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Medio de notificación",
                "verbose_name_plural": "Medios de notificación",
                "db_table": "medios_notificacion",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Modalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Modalidad",
                "verbose_name_plural": "Modalidades",
                "db_table": "modalidades",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NivelAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Nivel académico",
                "verbose_name_plural": "Niveles académicos",
                "db_table": "niveles_academicos",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SectorIndustrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Sector industrial",
                "verbose_name_plural": "Sectores industriales",
                "db_table": "sectores_industriales",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TamanoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tamaño de empresa",
                "verbose_name_plural": "Tamaños de empresa",
                "db_table": "tamanos_empresa",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de contrato",
                "verbose_name_plural": "Tipos de contrato",
                "db_table": "tipos_contrato",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de evento",
                "verbose_name_plural": "Tipos de evento",
                "db_table": "tipos_evento",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoInstitucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de institución",
                "verbose_name_plural": "Tipos de institución",
                "db_table": "tipos_institucion",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoPuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de puesto",
                "verbose_name_plural": "Tipos de puesto",
                "db_table": "tipos_puesto",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoVacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Tipo de vacante",
                "verbose_name_plural": "Tipos de vacante",
                "db_table": "tipos_vacante",
                "ordering": ["nombre"],
                "abstract": False,
            },
        ),
    ]
