# Generated by Django 5.2.11 on 2026-03-03 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "cedula_juridica",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Cédula jurídica",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "proceso_contratacion",
                    models.TextField(
                        blank=True, verbose_name="Proceso de contratación"
                    ),
                ),
                (
                    "tiene_url_externa",
                    models.BooleanField(
                        default=False, verbose_name="Tiene URL externa"
                    ),
                ),
                (
                    "url_externa",
                    models.URLField(blank=True, verbose_name="URL externa"),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True,
                        upload_to="empresas/perfil/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "contacto_interesados",
                    models.TextField(
                        blank=True, verbose_name="Contacto para interesados"
                    ),
                ),
                (
                    "contacto_admin",
                    models.TextField(
                        blank=True, verbose_name="Contacto administración"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ubicación"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Datos extra"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado_vacante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empresas",
                        to="catalogs.estadovacante",
                        verbose_name="Estado de vacante",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.sectorindustrial",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "tamano_empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogs.tamanoempresa",
                        verbose_name="Tamaño",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresa",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
            },
        ),
        migrations.CreateModel(
            name="GaleriaEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        upload_to="empresas/galeria/", verbose_name="Imagen"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galeria",
                        to="companies.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "galeria_empresa",
                "ordering": ["orden"],
            },
        ),
    ]
