export const CANTONES = [
  'Cartago', 'Paraíso', 'La Unión', 'Jiménez', 'Turrialba', 'Alvarado', 'Oreamuno', 'El Guarco'
];

export const MOCK_COMPANIES = [
  { id: '1', name: 'Intel Costa Rica', legalId: '3-101-123456', location: 'Cartago', phone: '2200-1111', email: 'ana@intel.com', contactName: 'Ana Smith', status: 'aprobada', registrationDate: '2024-01-15', vacanciesCount: 12 },
  { id: '2', name: 'Teradyne', legalId: '3-101-789012', location: 'La Unión', phone: '2200-2222', email: 'carlos@teradyne.com', contactName: 'Carlos Ruiz', status: 'pendiente', registrationDate: '2024-02-20', vacanciesCount: 0 },
  { id: '3', name: 'Edwards Lifesciences', legalId: '3-101-345678', location: 'Cartago', phone: '2200-3333', email: 'm.lopez@edwards.com', contactName: 'Maria Lopez', status: 'aprobada', registrationDate: '2023-11-05', vacanciesCount: 8 },
  { id: '4', name: 'SMC Ltd', legalId: '3-101-901234', location: 'El Guarco', phone: '2200-4444', email: 'jarias@smc.com', contactName: 'Jorge Arias', status: 'rechazada', registrationDate: '2024-02-10', vacanciesCount: 0 },
];

export const MOCK_INSTITUTIONS = [
  { id: '1', name: 'Tecnológico de Costa Rica (TEC)', type: 'universidad', location: 'Cartago', phone: '2550-2000', email: 'lperez@itcr.ac.cr', contactName: 'Luis Perez', status: 'aprobada', registrationDate: '2023-05-10', internsSent: 45 },
  { id: '2', name: 'CUC Cartago', type: 'centro_tecnico', location: 'Cartago', phone: '2550-3000', email: 'emora@cuc.ac.cr', contactName: 'Elena Mora', status: 'aprobada', registrationDate: '2023-08-22', internsSent: 30 },
  { id: '3', name: 'Universidad de Costa Rica', type: 'universidad', location: 'Paraíso', phone: '2511-1000', email: 'rsolis@ucr.ac.cr', contactName: 'Roberto Solis', status: 'pendiente', registrationDate: '2024-02-25', internsSent: 0 },
];

export const MOCK_ASPIRANTS = [
  {
    id: '1',
    name: 'Juan Diego Castro',
    email: 'jd.castro@gmail.com',
    phone: '8888-1111',
    status: 'activo',
    registrationDate: '2024-01-20',
    applicationsCount: 3,
    location: 'Cartago Centro',
    education: 'Bachillerato en Ingeniería en Computación - TEC',
    experience: '2 años como Desarrollador Junior en TechSolutions',
    softSkills: ['Comunicación Asertiva', 'Trabajo en Equipo', 'Resolución de Problemas'],
    hardSkills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript'],
    summary: 'Desarrollador apasionado por crear soluciones web eficientes y escalables.',
    resumeUrl: '#',
    institutionId: '1',
    institutionName: 'TEC',
    isPublic: true,
    sector: 'Tecnología',
    referenceProfessor: 'Ing. Luis Diego'
  },
  {
    id: '2',
    name: 'Sofía Méndez',
    email: 'sofia.m@outlook.com',
    phone: '7777-2222',
    status: 'activo',
    registrationDate: '2024-02-01',
    applicationsCount: 5,
    location: 'Paraíso',
    education: 'Licenciatura en Administración de Empresas - UCR',
    experience: '1 año de pasantía en Recursos Humanos',
    softSkills: ['Liderazgo', 'Organización', 'Empatía'],
    hardSkills: ['Gestión de Proyectos', 'Excel Avanzado', 'SAP'],
    summary: 'Profesional enfocada en la optimización de procesos administrativos.',
    resumeUrl: '#',
    institutionId: '2',
    institutionName: 'CUC',
    isPublic: true,
    sector: 'Administración',
    referenceProfessor: 'MSc. Jorge Castro'
  },
  {
    id: '3',
    name: 'Roberto Méndez',
    email: 'roberto.m@gmail.com',
    phone: '6666-3333',
    status: 'activo',
    registrationDate: '2023-12-15',
    applicationsCount: 0,
    location: 'El Guarco',
    education: 'Ingeniería Civil - UCR',
    experience: '3 años de experiencia en mantenimiento industrial',
    softSkills: ['Liderazgo', 'Comunicación', 'Resolución de conflictos'],
    hardSkills: ['AutoCAD', 'Gestión de Obras', 'Presupuestos'],
    summary: 'Ingeniero civil con enfoque en construcción y gestión de proyectos.',
    resumeUrl: '#',
    isPublic: true,
    sector: 'Construcción'
  },
  {
    id: '4',
    name: 'Valeria Solano',
    email: 'v.solano@gmail.com',
    phone: '5555-4444',
    status: 'activo',
    registrationDate: '2024-02-10',
    applicationsCount: 2,
    location: 'La Unión',
    education: 'Marketing Digital - ULACIT',
    experience: 'Freelance en redes sociales',
    softSkills: ['Trabajo en equipo', 'Adaptabilidad', 'Pensamiento crítico'],
    hardSkills: ['SEO', 'Google Ads', 'Copywriting'],
    summary: 'Estratega de marketing digital creativa y orientada a resultados.',
    resumeUrl: '#',
    isPublic: true,
    sector: 'Publicidad'
  },
  {
    id: '5',
    name: 'Andrés Castro',
    email: 'a.castro@gmail.com',
    phone: '4444-5555',
    status: 'activo',
    registrationDate: '2024-02-15',
    applicationsCount: 1,
    location: 'Jiménez',
    education: 'Recursos Humanos - UNED',
    experience: 'Asistente administrativo',
    softSkills: ['Empatía', 'Escucha activa', 'Paciencia'],
    hardSkills: ['Nómina', 'Legislación Laboral', 'Reclutamiento'],
    summary: 'Profesional de RRHH comprometido con el bienestar organizacional.',
    resumeUrl: '#',
    isPublic: true,
    sector: 'Servicios'
  },
  {
    id: '6',
    name: 'Jimena Alfaro',
    email: 'j.alfaro@tec.ac.cr',
    phone: '3333-6666',
    status: 'activo',
    registrationDate: '2024-02-20',
    applicationsCount: 4,
    location: 'Cartago',
    education: 'Ing. Electrónica - TEC',
    experience: 'Proyectos de robótica',
    softSkills: ['Análisis', 'Innovación'],
    hardSkills: ['Circuitos', 'IoT', 'C++'],
    summary: 'Estudiante avanzada de ingeniería electrónica con pasión por el IoT.',
    resumeUrl: '#',
    institutionId: '1',
    institutionName: 'TEC',
    isPublic: true,
    sector: 'Tecnología',
    referenceProfessor: 'Ing. Luis Diego'
  },
  /* {
    id: '7',
    name: 'Daniel Brenes',
    email: 'd.brenes@tec.ac.cr',
    phone: '2222-7777',
    status: 'activo',
    registrationDate: '2024-02-22',
    applicationsCount: 2,
    location: 'Cartago',
    education: 'Ing. Producción - TEC',
    experience: 'Pasantía en Intel',
    softSkills: ['Lean', 'Excel', 'SAP'],
    hardSkills: ['Optimización', 'Logística'],
    summary: 'Ingeniero de producción enfocado en la mejora continua.',
    resumeUrl: '#',
    institutionId: '1',
    institutionName: 'TEC',
    isPublic: true,
    sector: 'Producción',
    referenceProfessor: 'Ing. Marco Vinicio'
  }, */
];

export const MOCK_VACANCIES = [
  {
    id: '1',
    companyId: '1',
    companyName: 'Intel',
    title: 'Ingeniero de Software',
    description: 'Desarrollo de microprocesadores y optimización de algoritmos de bajo nivel.',
    type: 'empleo',
    status: 'aprobada',
    date: '2024-02-15',
    schedule: 'Lunes a Viernes',
    location: 'Zona Franca La Lima, Edificio B',
    requirements: ['Conocimiento en C++', 'Experiencia en sistemas embebidos', 'Inglés avanzado'],
    positionInfo: 'El puesto requiere disponibilidad para trabajar de forma presencial.',
    isFullTime: true,
    applicantsCount: 24,
    requestedBy: 'empresa',
    time: '08:00 AM - 05:00 PM'
  },
  {
    id: '2',
    companyId: '3',
    companyName: 'Edwards Lifesciences',
    title: 'Pasante de Calidad',
    description: 'Revisión y aseguramiento de calidad en dispositivos médicos de alta precisión.',
    type: 'pasantia',
    status: 'pendiente',
    date: '2024-02-26',
    schedule: 'Lunes a Jueves',
    location: 'Planta de Producción Cartago',
    requirements: ['Estudiante de Ingeniería Industrial', 'Atención al detalle', 'Conocimiento básico de ISO 13485'],
    positionInfo: 'Pasantía remunerada con posibilidad de contratación permanente.',
    isFullTime: false,
    applicantsCount: 12,
    requestedBy: 'institucion',
    time: '07:00 AM - 01:00 PM'
  },
  {
    id: '3',
    companyId: '1',
    companyName: 'Intel',
    title: 'Ingeniero de Calidad Jr.',
    description: 'Aseguramiento de calidad en procesos de manufactura de semiconductores.',
    type: 'empleo',
    status: 'aprobada',
    date: '2024-02-20',
    schedule: 'Lunes a Viernes',
    location: 'Cartago, Costa Rica',
    requirements: ['Ingeniería Industrial', 'Inglés B2', 'Conocimiento en Six Sigma'],
    positionInfo: 'Excelente oportunidad para recién graduados.',
    isFullTime: true,
    applicantsCount: 15,
    requestedBy: 'empresa',
    time: '08:00 AM - 05:00 PM'
  },
  {
    id: '4',
    companyId: '3',
    companyName: 'Edwards Lifesciences',
    title: 'Pasantía en Logística',
    description: 'Apoyo en la gestión de cadena de suministro y control de inventarios.',
    type: 'pasantia',
    status: 'aprobada',
    date: '2024-02-22',
    schedule: 'Lunes a Viernes',
    location: 'Cartago, Costa Rica',
    requirements: ['Estudiante de Logística', 'Disponibilidad inmediata', 'Excel intermedio'],
    positionInfo: 'Pasantía de 6 meses.',
    isFullTime: false,
    applicantsCount: 8,
    requestedBy: 'institucion',
    time: '07:00 AM - 02:00 PM'
  },
  {
    id: '5',
    companyId: '2',
    companyName: 'Teradyne',
    title: 'Senior Software Developer',
    description: 'Liderazgo técnico en proyectos de automatización de pruebas.',
    type: 'empleo',
    status: 'aprobada',
    date: '2024-02-25',
    schedule: 'Lunes a Viernes',
    location: 'Cartago, Costa Rica',
    requirements: ['5+ años experiencia', 'C++', 'Liderazgo de equipos'],
    positionInfo: 'Puesto con beneficios competitivos.',
    isFullTime: true,
    applicantsCount: 5,
    requestedBy: 'empresa',
    time: '09:00 AM - 06:00 PM'
  },
];

export const MOCK_ADMINS = [
  { id: '1', name: 'Admin Principal', email: 'admin@lalima.cr', role: 'superadmin', lastLogin: '2024-02-28 14:30' },
  { id: '2', name: 'Gestor de Contenido', email: 'gestor@lalima.cr', role: 'admin', lastLogin: '2024-02-27 09:15' },
];

export const MOCK_AUDIT = [
  { id: '1', action: 'Aprobación de Empresa', userName: 'Admin Principal', userRole: 'Superadmin', target: 'Intel Costa Rica', timestamp: '2024-02-28 14:30', type: 'cambio' },
  { id: '2', action: 'Nueva Vacante Publicada', userName: 'Maria Lopez', userRole: 'Empresa', target: 'Edwards Lifesciences', timestamp: '2024-02-28 10:15', type: 'solicitud' },
  { id: '3', action: 'Solicitud de Pasantía', userName: 'Luis Perez', userRole: 'Institución', target: 'Tecnológico de Costa Rica', timestamp: '2024-02-28 09:00', type: 'solicitud' },
  { id: '4', action: 'Edición de Perfil', userName: 'Admin Principal', userRole: 'Superadmin', target: 'Juan Diego Castro', timestamp: '2024-02-27 16:45', type: 'cambio' },
];