# Generated by Django 5.2.11 on 2026-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucion",
            name="activa",
            field=models.BooleanField(default=False),
        ),
    ]
